### NumPy First Steps

### Programming for Data Science
### Last Updated: Jan 15, 2023
---  

### PREREQUISITES
- import
- functions
- for ... in

### SOURCES 
- **Python for Data Analysis, Chapter 4 (be sure to read this)**
- https://numpy.org/
- https://en.wikipedia.org/wiki/NumPy
- https://www.scipy.org/
- https://en.wikipedia.org/wiki/SciPy
- https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html
- https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html

### OBJECTIVES
- Take your first steps with numpy
 


### CONCEPTS

- The numpy package contains useful functions for math operations
- The ndarray is the workhorse of the package


---

### numpy

In this lesson we will explore the python package *numpy*.  
This package is super powerful. 

Our focus will be on:
- importing and calling some random number generating functions
- illustrating operations on ndarrays
- learning how to subset ndarrays

### Motivation

I need a random number! I heard numpy can do that!  

In [81]:
import numpy as np
np.random.randint(1,7)

2

Learn what this function does:

In [7]:
help(np.random.randint)

Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
     

Include the size parameter to generate 10 random integers in [1, 6]

In [9]:
np.random.randint(1,7,10)

array([5, 2, 6, 6, 1, 4, 1, 3, 5, 2])

---

### The ndarray in Numpy

Details [here](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html)

Represents a multidimensional, homogeneous array of fixed-size items. 

Uses very efficient operations

Arrays should be constructed using `array()`, `zeros()` or `empty()`.

### NumPy ndarray Operations


Create an array with some data

In [11]:
x = np.array(([2,3,1],[3,1,2]))
x

array([[2, 3, 1],
       [3, 1, 2]])

Get the shape of the data (rows, columns)

In [13]:
print(x.shape)

(2, 3)


In [83]:
# generate matrix of random normals 

x = np.random.randn(2, 3)
x

array([[ 0.28203858, -0.0744902 , -0.21986194],
       [-0.37153866, -0.1542944 , -0.16678512]])

In [85]:
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)

    Return a sample (or samples) from the "standard normal" distribution.

    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.

    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned

Scale the matrix - notice how this operates elementwise

In [91]:
x * 2

array([[ 0.56407717, -0.14898041, -0.43972388],
       [-0.74307733, -0.3085888 , -0.33357024]])

Addition

In [93]:
x + x

array([[ 0.56407717, -0.14898041, -0.43972388],
       [-0.74307733, -0.3085888 , -0.33357024]])

Reciprocal

In [95]:
1 / x

array([[  3.54561419, -13.42458411,  -4.54830886],
       [ -2.69150992,  -6.48111664,  -5.99573869]])

#### Creating Matrices with Special Structure - can create arrays of zeros, ones, and identity matrices

In [97]:
x=np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [99]:
x.shape

(5,)

In [101]:
y=np.zeros([5,1])

In [103]:
y

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [105]:
y.shape

(5, 1)

In [107]:
z=np.zeros([1,5])
print(z)

[[0. 0. 0. 0. 0.]]


In [109]:
z.shape

(1, 5)

In [111]:
q=np.zeros((2,3))
print(q)

[[0. 0. 0.]
 [0. 0. 0.]]


In [113]:
q.shape

(2, 3)

In [115]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [117]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Indexing and Slicing

In [119]:
z = np.random.randn(5)
z

array([ 1.50730694,  0.10724493,  0.4972593 , -0.6539114 ,  0.85079975])

In [121]:
# select from start to one before end
z[1:4]

array([ 0.10724493,  0.4972593 , -0.6539114 ])

In [123]:
# does this make sense?
z[1:-1]

array([ 0.10724493,  0.4972593 , -0.6539114 ])

In [125]:
# boolean indexing
z[z>0.15]

array([1.50730694, 0.4972593 , 0.85079975])

In [127]:
# assignment
z[1] = 3
z

array([ 1.50730694,  3.        ,  0.4972593 , -0.6539114 ,  0.85079975])

In [129]:
# 2D
w = np.random.randn(3,3)
w


array([[ 0.44410336, -2.17204873, -0.83529447],
       [ 1.22204085,  0.59433084, -1.04815265],
       [-1.14210171,  2.9941762 ,  0.19501397]])

In [131]:
# subset rows and columns
w[1:, :2]

array([[ 1.22204085,  0.59433084],
       [-1.14210171,  2.9941762 ]])

#### TRY FOR YOURSELF
Write code to generate a new array *w2* that starts with *w* and sets all negative values to 0.
Then print *w2* and *w*.  

Be sure to use:  
w2 = w.copy()  
or w will get updated as well

In [133]:
w2 = w.copy()
w2[w2 < 0] = 0
print('w2:\n', w2)
print('')
print('w:\n', w)

w2:
 [[0.44410336 0.         0.        ]
 [1.22204085 0.59433084 0.        ]
 [0.         2.9941762  0.19501397]]

w:
 [[ 0.44410336 -2.17204873 -0.83529447]
 [ 1.22204085  0.59433084 -1.04815265]
 [-1.14210171  2.9941762   0.19501397]]


In [135]:
w2 = w
w2[w2 < 0] = 0
print('w2:\n', w2)
print('')
print('w:\n', w)


w2:
 [[0.44410336 0.         0.        ]
 [1.22204085 0.59433084 0.        ]
 [0.         2.9941762  0.19501397]]

w:
 [[0.44410336 0.         0.        ]
 [1.22204085 0.59433084 0.        ]
 [0.         2.9941762  0.19501397]]


---  

#### Next Steps

This notebook provided some information to get you started.

To learn more, please refer to your textbook and the links in the Sources section at top.